/* global React, Ico */
const { useState: useS1 } = React;

// ============= DATA =============
window.VS_DATA = {
  campaign: { name: 'Shadows Over Eldoria', world: 'Eldoria' },
  presence: [
    { id: 'gm', initials: 'VS', role: 'gm', name: 'You (GM)' },
    { id: 'p1', initials: 'KM', role: 'p1', name: 'Kira (Rogue)' },
    { id: 'p2', initials: 'TH', role: 'p2', name: 'Thorn (Druid)' },
    { id: 'p3', initials: 'LY', role: 'p3', name: 'Lyra (Cleric)' },
    { id: 'p4', initials: '+2', role: 'more', name: '2 more' },
  ],
  locations: [
    { id: 'citadel', name: 'Shattered Citadel', icon: 'castle', region: 'Northmarch', pop: '8,000', climate: 'Temperate', danger: 'High Danger', visibility: 'player', hero: true,
      desc: 'Once the seat of the Solar Kings, now a hollowed shell inhabited by things that feed on echoes.',
      tags: ['ruined', 'haunted'], image: 'citadel' },
    { id: 'voidpeaks', name: 'Void Peaks', icon: 'mountain', desc: 'Where gravity begins to fail…', updated: '2H AGO', visibility: 'gm', tags: ['danger'] },
    { id: 'whispering', name: 'Whispering Woods', icon: 'tree', desc: 'The trees remember your name.', visibility: 'gm', tags: ['GM Only'] },
    { id: 'docks', name: 'Kaedon Docks', icon: 'anchor', desc: 'Smugglers and sea salt.', visibility: 'player', updated: 'DEC 12' },
    { id: 'ironkeep', name: 'Iron Keep', icon: 'castle', desc: 'Impenetrable, or so they say.', progress: 75, visibility: 'player' },
    { id: 'moonshrine', name: 'Moon Shrine', icon: 'crown', desc: 'Only visible during the eclipse.', updated: 'YESTERDAY', visibility: 'gm' },
    { id: 'ashenvale', name: 'Ashenvale', icon: 'fire', desc: 'Perpetual twilight. Ash falls like snow.', visibility: 'player', tags: ['mystery'] },
    { id: 'emberport', name: 'Emberport', icon: 'anchor', desc: 'Free city. All creeds welcome, all debts collected.', pop: '42,000', visibility: 'player', tags: ['city'] },
  ],
  pins: [
    { id: 'citadel', x: 62, y: 45, type: 'city', label: 'Shattered Citadel' },
    { id: 'iron', x: 71, y: 58, type: 'faction', label: 'Iron Keep' },
    { id: 'whisp', x: 44, y: 40, type: 'landmark', label: 'Whispering Woods' },
    { id: 'docks', x: 48, y: 62, type: 'city', label: 'Kaedon Docks' },
    { id: 'void', x: 78, y: 28, type: 'landmark', label: 'Void Peaks' },
    { id: 'moon', x: 33, y: 55, type: 'quest', label: 'Moon Shrine' },
    { id: 'malakor', x: 66, y: 48, type: 'npc', label: 'Lord Malakor' },
    { id: 'ember', x: 52, y: 72, type: 'city', label: 'Emberport' },
  ],
  timeline: [
    { era: 'Age of Ash', range: '-∞ – 0 CY', active: false },
    { era: 'Age of Fire', range: '0 – 220 CY', active: true },
    { era: 'Age of Silence', range: '220 CY – now', active: false },
  ],
  events: [
    { id: 'shatter', side: 'left', date: 'Ice Season, 42nd CY', title: 'The Shattering', tags: [['cosmic','COSMIC'],['cataclysm','CATACLYSM']],
      desc: 'The celestial vault cracked, raining crystal shards across the frozen north. The first dragons emerged from the rifts.', icon: 'zap' },
    { id: 'siege', side: 'right', date: 'Spring, 115th CY', title: 'Siege of Northfall', tags: [['combat','COMBAT'],['intrigue','MAJOR CONFLICT']],
      desc: 'A bloody three-month stalemate between the Iron Lords and the Frost-kin. Ended by a surprise betrayal.', icon: 'swords' },
    { id: 'burning', side: 'left', date: 'Harvest, 168th CY', title: 'Order of the Burning Chalice', tags: [['cataclysm','FOUNDING']],
      desc: 'Twelve mages swore an oath in the ruins of Old Temple, binding themselves to defend the Citadel.', icon: 'fire' },
    { id: 'crown', side: 'right', date: 'Ice Season, 201st CY', title: 'Fall of the Solar Crown', tags: [['combat','COMBAT'],['player','PLAYERS PRESENT']],
      desc: 'The last Solar King was found dead in his tower. The crown vanished. The Citadel shattered the next day.', icon: 'crown' },
    { id: 'pact', side: 'left', date: 'Ember, 218th CY', title: 'The Kaedon Pact', tags: [['intrigue','INTRIGUE']],
      desc: 'Smuggler-lords and merchant princes signed a truce in the salt caves. The Iron Circle was not invited.', icon: 'scroll' },
  ],
  npcs: [
    { id: 'malakor', name: 'Lord Malakor', title: 'The Hollow Regent of the Shattered Citadel',
      species: 'Human (undying)', role: 'Antagonist', threat: 'Legendary', visibility: 'GM Only' },
  ],
  factions: [
    { id: 'iron', name: 'The Iron Circle', size: 12, x: 15, y: 30, color: '#e0566a', sigil: 'shield' },
    { id: 'chalice', name: 'Order of the Burning Chalice', size: 8, x: 50, y: 20, color: '#e6a255', sigil: 'fire' },
    { id: 'solar', name: 'Solar Remnants', size: 5, x: 75, y: 45, color: '#e6d255', sigil: 'crown' },
    { id: 'kaedon', name: 'Kaedon Pact', size: 10, x: 30, y: 65, color: '#4ec8c0', sigil: 'anchor' },
    { id: 'void', name: 'Children of Void', size: 6, x: 65, y: 75, color: '#8b5cf6', sigil: 'sparkle' },
    { id: 'frost', name: 'Frost-kin', size: 7, x: 85, y: 75, color: '#6b8af0', sigil: 'mountain' },
  ],
  party: [
    {
      id: 'kira', name: 'Kira Vex', player: 'Kira M.', initials: 'KM', role: 'p1',
      race: 'Half-elf', class: 'Rogue (Assassin)', level: 5, alignment: 'Chaotic Neutral',
      hp: 34, hpMax: 38, ac: 16, speed: 35, passive: 16, prof: 3,
      stats: { STR: 10, DEX: 18, CON: 12, INT: 13, WIS: 11, CHA: 14 },
      saves: ['DEX', 'INT'],
      bg: 'Criminal', xp: 6500, xpNext: 14000,
      color: 'linear-gradient(135deg, #4ec8c0, #2a7a75)',
      hooks: ['Owes 800gp to the Kaedon Pact', 'Sister vanished in the Citadel'],
      inventory: ['Daggers of Venom ×2', 'Thieves\' tools', 'Cloak of Elvenkind'],
      status: ['Poisoned ×2 charges'],
      sheetLink: 'dndbeyond.com/characters/kira',
    },
    {
      id: 'thorn', name: 'Thorn Greenbough', player: 'Thorn H.', initials: 'TH', role: 'p2',
      race: 'Wood Elf', class: 'Druid (Circle of Moon)', level: 5, alignment: 'Neutral Good',
      hp: 42, hpMax: 42, ac: 14, speed: 35, passive: 17, prof: 3,
      stats: { STR: 8, DEX: 14, CON: 14, INT: 12, WIS: 18, CHA: 10 },
      saves: ['INT', 'WIS'],
      bg: 'Outlander', xp: 7200, xpNext: 14000,
      color: 'linear-gradient(135deg, #e6a255, #a86a2a)',
      hooks: ['Sworn to restore the Whispering Woods', 'Distrusts the Chalice'],
      inventory: ['Shillelagh staff', 'Druidic focus (acorn)', 'Herbalism kit'],
      status: [],
      sheetLink: 'dndbeyond.com/characters/thorn',
    },
    {
      id: 'lyra', name: 'Lyra Dawnmere', player: 'Lyra Y.', initials: 'LY', role: 'p3',
      race: 'Human', class: 'Cleric (Light Domain)', level: 5, alignment: 'Lawful Good',
      hp: 38, hpMax: 40, ac: 18, speed: 30, passive: 13, prof: 3,
      stats: { STR: 12, DEX: 10, CON: 14, INT: 11, WIS: 18, CHA: 15 },
      saves: ['WIS', 'CHA'],
      bg: 'Acolyte', xp: 6800, xpNext: 14000,
      color: 'linear-gradient(135deg, #e0566a, #a03040)',
      hooks: ['Hears whispers from the Solar Crown', 'Novice of the Burning Chalice'],
      inventory: ['Mace +1', 'Holy symbol (sun disc)', 'Scroll of Daylight'],
      status: ['Blessed (until long rest)'],
      sheetLink: 'dndbeyond.com/characters/lyra',
    },
    {
      id: 'brann', name: 'Brann Stonefist', player: 'Alex R.', initials: 'AR', role: 'p4',
      race: 'Mountain Dwarf', class: 'Fighter (Battle Master)', level: 5, alignment: 'Lawful Neutral',
      hp: 48, hpMax: 52, ac: 19, speed: 25, passive: 12, prof: 3,
      stats: { STR: 17, DEX: 12, CON: 16, INT: 10, WIS: 13, CHA: 8 },
      saves: ['STR', 'CON'],
      bg: 'Soldier', xp: 7000, xpNext: 14000,
      color: 'linear-gradient(135deg, #b38a5a, #5e4a30)',
      hooks: ['Hunts the killer of his Iron Circle squad', 'Owes a debt to Tam the Ferryman'],
      inventory: ['Warhammer +1', 'Plate mail', 'Shield of the Iron Hand'],
      status: [],
      sheetLink: 'dndbeyond.com/characters/brann',
    },
  ],
  partyNotes: [
    { id: 'n1', author: 'GM', color: 'gm', time: '2 days ago', body: 'Malakor\'s first appearance: when they open the vault, NOT before. Describe the shadow with no source.' },
    { id: 'n2', author: 'Kira', color: 'p1', time: '1 day ago', body: 'Can we session zero the Kaedon debt? I want to play into it — maybe a collector shows up mid-session.' },
    { id: 'n3', author: 'Thorn', color: 'p2', time: '12h ago', body: 'Prepared Pass Without Trace for Saturday. Assume stealth rolls are fine.' },
    { id: 'n4', author: 'Lyra', color: 'p3', time: '6h ago', body: 'Down to 2 spell slots going into the session. Will long rest first.' },
  ],
  partyQuestHooks: [
    { id: 'qh1', title: "Malakor's Secret", body: 'Find out what the Hollow Regent wants with the Solar Crown — and whether he is the same man who vanished in 201 CY.', priority: 'main', linked: ['Lord Malakor', 'Shattered Citadel'] },
    { id: 'qh2', title: "Kira's Sister", body: 'Amara vanished into the Citadel two winters ago. Rumors of a pale figure seen in the east wing.', priority: 'personal', owner: 'kira', linked: ['Shattered Citadel'] },
    { id: 'qh3', title: 'The Kaedon Debt', body: '800gp owed to the Pact — collector surfaces after Session 14. Choice: pay, run, or break the contract.', priority: 'side', owner: 'kira', linked: ['Kaedon Pact'] },
    { id: 'qh4', title: 'Restore the Whispering Woods', body: "Thorn's druidic oath. The wood remembers — but something older has taken root at its heart.", priority: 'personal', owner: 'thorn', linked: ['Whispering Woods'] },
    { id: 'qh5', title: 'Voice of the Crown', body: "Lyra hears it at dawn. Is it the crown calling, or the thing that wore it last?", priority: 'personal', owner: 'lyra', linked: ['Solar Remnants'] },
  ],
  partyLoot: [
    { id: 'l1', name: 'Sunfang Dagger', rarity: 'Uncommon', desc: '+1, sheds light in darkness. Claimed by party.', holder: 'kira', icon: 'swords' },
    { id: 'l2', name: 'Map to Old Temple', rarity: 'Quest', desc: 'Half-burned parchment, pointing past the Void Peaks.', holder: 'shared', icon: 'scroll' },
    { id: 'l3', name: 'Amulet of the Solar Line', rarity: 'Rare', desc: 'Glows near Solar Remnants. Origin unknown.', holder: 'lyra', icon: 'crown' },
    { id: 'l4', name: 'Pouch of Smuggler\'s Dust', rarity: 'Common', desc: '3 charges. Creates a coughing cloud (10ft radius).', holder: 'shared', icon: 'sparkle' },
    { id: 'l5', name: 'Iron Circle Seal', rarity: 'Quest', desc: 'Grants safe passage through Iron Circle checkpoints — once.', holder: 'brann', icon: 'shield' },
    { id: 'l6', name: 'Pact-marked Coin', rarity: 'Uncommon', desc: 'Whistling silver. Speaks debts aloud when flipped.', holder: 'shared', icon: 'star' },
  ],
  partyRelationships: [
    // Inter-party and NPC relationships
    { from: 'kira', to: 'lyra', type: 'rival', note: 'Disagrees on Chalice methods' },
    { from: 'thorn', to: 'brann', type: 'trust', note: 'Saved him in Northmarch' },
    { from: 'kira', to: 'brann', type: 'wary', note: 'Iron Circle history' },
    { from: 'lyra', to: 'thorn', type: 'ally', note: 'Healing partnership' },
  ],
  factionEdges: [
    ['iron', 'chalice', 'ally'],
    ['iron', 'kaedon', 'enemy'],
    ['iron', 'solar', 'enemy'],
    ['chalice', 'solar', 'ally'],
    ['void', 'chalice', 'enemy'],
    ['void', 'frost', 'ally'],
    ['kaedon', 'chalice', 'neutral'],
    ['frost', 'iron', 'enemy'],
  ],
};
